language: node_js
node_js:
  - "node"
services: mongodb

before_script:
  - "npm install"

jdk:
  - oraclejdk8
addons:
  sonarcloud: true


script:
  - npm test
  - sonar-scanner -Dsonar.login=833a5b9f41b56c13ab75b1db5f70b898fabbd42e -Dsonar.organization=waristi-github -Dsonar.language=javascript -Dsonar.projectKey=ceamapp -Dsonar.sources="./routes ./models ./app.js" -X

